api:
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

  ws:
    address: ":3000"

  redis:
    address: ":6379"